const games = {
    // Популярные
    rdr2: {
        title_ru: 'Red Dead Redemption 2',
        title_en: 'Red Dead Redemption 2',
        desc_ru: 'Действие происходит в 1899 году. Артур Морган и банда Ван дер Линде вынуждены бежать после неудачного ограбления. Им предстоит бороться за выживание в жестоком мире Дикого Запада, сталкиваясь с федеральными агентами, знаменитыми бандитами и личными демонами. Огромный открытый мир с невероятной детализацией, система чести влияет на сюжет, охота, рыбалка, грабежи поездов и множество побочных активностей.',
        desc_en: 'Set in 1899, Arthur Morgan and the Van der Linde gang are on the run after a failed heist. They must fight for survival in the brutal world of the Wild West, facing federal agents, famous outlaws, and personal demons. A massive open world with incredible detail, honor system affecting the story, hunting, fishing, train robberies, and numerous side activities.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-2500K / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 770 2GB / AMD Radeon R9 280 3GB', 'Место: 150 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-4770K / AMD Ryzen 5 1500X', 'ОЗУ: 12 GB', 'Видеокарта: Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB', 'Место: 150 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: "Игра очень требовательна к видеопамяти. Если у вас меньше 6ГБ VRAM, снизьте качество текстур.",
        doctor_advice_en: "The game is very demanding on VRAM. If you have less than 6GB VRAM, reduce texture quality.",
        year: 2018,
        developer: 'Rockstar Games',
        genres: ['Action', 'Adventure'],
        playtime_main: 48,
        playtime_completion: 178,
        metacritic: 97,
        steam: 'Очень положительные',
        ign: '10/10',
        build: {
            cpu: 'Intel Core i7-12700K',
            gpu: 'NVIDIA RTX 3070',
            ram: 32
        },
        trailer: 'https://www.youtube.com/embed/gmA6MrX81z4'
    },
    cyberpunk: {
        title_ru: 'Cyberpunk 2077',
        title_en: 'Cyberpunk 2077',
        desc_ru: 'Найт-Сити, 2077 год. Вы — Ви, наёмник, ищущий уникальный имплант, который может стать ключом к бессмертию. Исследуйте огромный открытый мир, наполненный корпоративными интригами, уличными бандами и высокими технологиями. Настраивайте персонажа под свой стиль игры: стрелок, нетраннер или ниндзя с киберимплантами. Благодаря обновлению 2.0 и дополнению Phantom Liberty игра достигла того уровня, который обещали изначально.',
        desc_en: 'Night City, 2077. You are V, a mercenary looking for a unique implant that may be the key to immortality. Explore a massive open world filled with corporate intrigue, street gangs, and high technology. Customize your character to fit your playstyle: gunner, netrunner, or ninja with cyberimplants. With the 2.0 update and Phantom Liberty expansion, the game has reached the level originally promised.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-6700 / AMD Ryzen 5 1600', 'ОЗУ: 12 GB', 'Видеокарта: Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 580 8GB', 'Место: 70 GB SSD'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-12700 / AMD Ryzen 7 7800X3D', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 2060 SUPER / AMD Radeon RX 5700 XT', 'Место: 70 GB SSD'],
        power_rank: 8,
        rtx_supported: true,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: "Для трассировки лучей нужна RTX-видеокарта. На минималках пойдёт на GTX 1060, но с FSR.",
        doctor_advice_en: "Ray tracing requires an RTX graphics card. On minimum settings, it will run on GTX 1060 with FSR.",
        year: 2020,
        developer: 'CD Projekt Red',
        genres: ['RPG', 'Shooter'],
        playtime_main: 25,
        playtime_completion: 105,
        metacritic: 86,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i5-12400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/8X2kIfS6fb8'
    },
    daysgone: {
        title_ru: 'Days Gone',
        title_en: 'Days Gone',
        desc_ru: 'Постапокалипсис. Байкер Дикон Сент-Джон пытается выжить в мире, захваченном ордами фрикеров — заражённых людей, превратившихся в агрессивных существ. Исследуйте леса Орегона на своём мотоцикле, улучшайте его, сражайтесь с бандитами и помогайте другим выжившим. Главная фишка игры — огромные орды фрикеров, которых можно заманивать в ловушки и уничтожать десятками.',
        desc_en: 'Post-apocalypse. Biker Deacon St. John tries to survive in a world overrun by hordes of Freakers — infected humans turned into aggressive creatures. Explore the forests of Oregon on your motorcycle, upgrade it, fight bandits, and help other survivors. The game\'s main feature is the massive hordes of Freakers that can be lured into traps and destroyed by the dozens.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1259420/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-2500K / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 780 3GB / AMD Radeon R9 290 4GB', 'Место: 70 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-4770K / AMD Ryzen 5 1500X', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 580 8GB', 'Место: 70 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: "Игра оптимизирована, но при большом количестве врагов может проседать FPS. Рекомендуется 16 ГБ ОЗУ.",
        doctor_advice_en: "The game is optimized, but FPS may drop with a large number of enemies. 16 GB RAM recommended.",
        year: 2019,
        developer: 'Bend Studio',
        genres: ['Action', 'Horror'],
        playtime_main: 36,
        playtime_completion: 60,
        metacritic: 71,
        steam: 'Очень положительные',
        ign: '6.5/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 3050',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/FKtaOY9lMvM'
    },
    gta5: {
        title_ru: 'Grand Theft Auto V',
        title_en: 'Grand Theft Auto V',
        desc_ru: 'Лос-Сантос — город солнца, знаменитостей и проблем. Трое совершенно разных преступников объединяются для серии дерзких ограблений. Майкл — бывший грабитель, живущий в скуке и роскоши. Франклин — уличный бандит, ищущий возможности вырваться из нищеты. Тревор — психопат-наркоман с собственным бизнесом в пустыне. Огромный открытый мир с кучей активностей, отличный сюжет и легендарный мультиплеер GTA Online.',
        desc_en: 'Los Santos — a city of sun, celebrities, and problems. Three completely different criminals team up for a series of daring heists. Michael — a former robber living in boredom and luxury. Franklin — a street gangster looking for a way out of poverty. Trevor — a psychopathic drug addict with his own business in the desert. A huge open world with tons of activities, a great story, and the legendary GTA Online multiplayer.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core 2 Quad Q6600 / AMD Phenom 9850', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce 9800 GT / AMD Radeon HD 4870', 'Место: 72 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-3470 / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 72 GB'],
        power_rank: 5,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: "GTA V хорошо работает даже на старых ПК. Если у вас слабая видеокарта, снизьте настройки травы и теней.",
        doctor_advice_en: "GTA V runs well even on older PCs. If you have a weak graphics card, lower grass and shadow settings.",
        year: 2013,
        developer: 'Rockstar Games',
        genres: ['Action', 'Adventure'],
        playtime_main: 32,
        playtime_completion: 84,
        metacritic: 97,
        steam: 'Очень положительные',
        ign: '10/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/QkkoHAzjnUs'
    },
    ghost: {
        title_ru: 'Ghost of Tsushima',
        title_en: 'Ghost of Tsushima',
        desc_ru: '1274 год. Монгольская империя вторгается на остров Цусима, уничтожая самураев на своём пути. Самурай Дзин Сакаи — один из немногих выживших. Он вынужден отказаться от кодекса чести самурая, чтобы защитить свой народ, став легендарным Призраком. Исследуйте прекрасный открытый мир феодальной Японии, сражайтесь с монголами в стелсе или открытом бою, находите союзников и вдохновляйте людей на сопротивление.',
        desc_en: '1274. The Mongol Empire invades Tsushima island, destroying the samurai in its path. Samurai Jin Sakai is one of the few survivors. He must abandon the samurai code of honor to protect his people, becoming the legendary Ghost. Explore the beautiful open world of feudal Japan, fight the Mongols in stealth or open combat, find allies, and inspire the people to resist.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i3-7100 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 960 / AMD Radeon RX 5500 XT', 'Место: 75 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-8600 / AMD Ryzen 5 3600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 2060 / AMD Radeon RX 5600 XT', 'Место: 75 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: "Порт отличный, но для 4K потребуется мощная видеокарта. На средних настройках пойдёт на GTX 1060.",
        doctor_advice_en: "Great port, but 4K requires a powerful graphics card. It will run on GTX 1060 at medium settings.",
        year: 2020,
        developer: 'Sucker Punch Productions',
        genres: ['Action', 'Adventure'],
        playtime_main: 25,
        playtime_completion: 55,
        metacritic: 83,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/zo4Xbmgo0do'
    },
    witcher3: {
        title_ru: 'Ведьмак 3: Дикая Охота',
        title_en: 'The Witcher 3: Wild Hunt',
        desc_ru: 'Геральт из Ривии, профессиональный охотник на чудовищ, отправляется в путешествие по огромному открытому миру, чтобы найти свою приёмную дочь Цири. Эпическая RPG с нелинейным сюжетом, где каждое решение имеет последствия. Два масштабных дополнения — «Каменные сердца» и «Кровь и вино» — добавляют десятки часов геймплея.',
        desc_en: 'Geralt of Rivia, a professional monster slayer, embarks on a journey through a massive open world to find his adopted daughter Ciri. An epic RPG with a non-linear story where every decision has consequences. Two massive expansions — Hearts of Stone and Blood and Wine — add dozens of hours of gameplay.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
        min: ['ОС: Windows 7/8/10 64-bit', 'Процессор: Intel Core i5-2500K / AMD Phenom II X4 940', 'ОЗУ: 6 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 35 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-3770 / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 770 / AMD Radeon R9 290', 'Место: 35 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Игра хорошо оптимизирована, но в крупных городах может проседать FPS. Для высоких настроек нужно 2+ ГБ VRAM.',
        doctor_advice_en: 'The game is well optimized, but FPS may drop in large cities. For high settings you need 2+ GB VRAM.',
        year: 2015,
        developer: 'CD Projekt RED',
        genres: ['RPG', 'Action'],
        playtime_main: 52,
        playtime_completion: 175,
        metacritic: 93,
        steam: 'Очень положительные',
        ign: '9.3/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 2060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/A-mCKNTU_mU'
    },
    dyinglight2: {
        title_ru: 'Dying Light 2: Stay Human',
        title_en: 'Dying Light 2: Stay Human',
        desc_ru: 'Спустя 20 лет после событий первой игры человечество продолжает выживать в мире, охваченном зомби-апокалипсисом. Эйден Колдуэлл, странник с навыками паркура, пытается найти свою сестру. Ваш выбор формирует город и фракции, а динамическая смена дня и ночи меняет поведение врагов.',
        desc_en: '20 years after the first game, humanity continues to survive in a world gripped by a zombie apocalypse. Aiden Caldwell, a pilgrim with parkour skills, tries to find his sister. Your choices shape the city and factions, and the dynamic day-night cycle changes enemy behavior.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/534380/header.jpg',
        min: ['ОС: Windows 7 64-bit', 'Процессор: Intel Core i3-9100 / AMD Ryzen 3 2300X', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 1050 Ti / AMD Radeon RX 560 (4GB VRAM)', 'Место: 60 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-8600K / AMD Ryzen 5 3600X', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 2060 / AMD Radeon RX Vega 56 (6GB VRAM)', 'Место: 60 GB SSD'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к видеокарте, особенно при трассировке лучей. Рекомендуется 16+ ГБ ОЗУ и SSD.',
        doctor_advice_en: 'Demanding on GPU, especially with ray tracing. 16+ GB RAM and SSD recommended.',
        year: 2022,
        developer: 'Techland',
        genres: ['Action', 'RPG', 'Survival'],
        playtime_main: 25,
        playtime_completion: 100,
        metacritic: 76,
        steam: 'Очень положительные',
        ign: '7/10',
        build: {
            cpu: 'Intel Core i5-12400F',
            gpu: 'NVIDIA RTX 3060 Ti',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/68bZ1LKKh7Q'
    },
    ark: {
        title_ru: 'Ark: Survival Evolved',
        title_en: 'Ark: Survival Evolved',
        desc_ru: 'Проснитесь на таинственном острове, населённом динозаврами и доисторическими существами. Вам предстоит охотиться, собирать ресурсы, строить убежища, приручать и разводить динозавров, а также сражаться с другими игроками в огромном открытом мире. Игра поддерживает одиночный режим и многопользовательскую игру.',
        desc_en: 'Wake up on a mysterious island populated by dinosaurs and prehistoric creatures. You must hunt, gather resources, build shelters, tame and breed dinosaurs, and fight other players in a massive open world. The game supports single-player and multiplayer modes.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/346110/header.jpg',
        min: ['ОС: Windows 7/8.1/10 64-bit', 'Процессор: Intel Core i5-2400 / AMD FX-8320', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 670 / AMD Radeon HD 7870 (2GB VRAM)', 'Место: 60 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-4770 / AMD Ryzen 5 2600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 980 / AMD Radeon R9 390 (4GB VRAM)', 'Место: 60 GB SSD'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Ark очень требователен к процессору, особенно в мультиплеере с большими базами. Рекомендуется 16+ ГБ ОЗУ и SSD для быстрой загрузки.',
        doctor_advice_en: 'Ark is very CPU intensive, especially in multiplayer with large bases. 16+ GB RAM and SSD recommended for fast loading.',
        year: 2017,
        developer: 'Studio Wildcard',
        genres: ['Survival', 'Open World', 'Crafting'],
        playtime_main: 30,
        playtime_completion: 200,
        metacritic: 70,
        steam: 'Смешанные',
        ign: '7/10',
        build: {
            cpu: 'AMD Ryzen 5 5600X',
            gpu: 'NVIDIA RTX 3060',
            ram: 32
        },
        trailer: 'https://www.youtube.com/embed/FW9vsrPWujI'
    },
    // Assassin's Creed
    ac1: {
        title_ru: 'Assassin\'s Creed',
        title_en: 'Assassin\'s Creed',
        desc_ru: '1191 год. Эпоха Третьего крестового похода. Альтаир ибн-Ла-Ахад, ассасин, потерявший статус после провала миссии, получает шанс искупить вину. Ему предстоит устранить девять целей по всему Святой Земле, включая Иерусалим, Дамаск и Акру. Игра заложила основы серии: паркур, скрытные убийства и расследования. Начало легендарной истории Братства.',
        desc_en: '1191. The era of the Third Crusade. Altaïr Ibn-LaʼAhad, an Assassin who lost his rank after a failed mission, gets a chance to redeem himself. He must eliminate nine targets across the Holy Land, including Jerusalem, Damascus, and Acre. The game laid the foundations of the series: parkour, stealth assassinations, and investigations. The beginning of the legendary Brotherhood story.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/15100/header.jpg',
        min: ['ОС: Windows XP/Vista', 'Процессор: Intel Pentium D 3.0 GHz / AMD Athlon 64 X2 3800+', 'ОЗУ: 1 GB', 'Видеокарта: Nvidia GeForce 6800 / ATI Radeon X1300', 'Место: 8 GB'],
        rec: ['ОС: Windows XP/Vista', 'Процессор: Intel Core 2 Duo 2.2 GHz / AMD Athlon 64 X2 4400+', 'ОЗУ: 2 GB', 'Видеокарта: Nvidia GeForce 8800 / ATI Radeon HD 3870', 'Место: 8 GB'],
        power_rank: 3,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Первая часть, работает на любом современном ПК.',
        doctor_advice_en: 'The first part, runs on any modern PC.',
        year: 2007,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Stealth'],
        playtime_main: 15,
        playtime_completion: 25,
        metacritic: 79,
        steam: 'Очень положительные',
        ign: '7.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/RjQ6ZtyXoA0'
    },
    ac2: {
        title_ru: 'Assassin\'s Creed II',
        title_en: 'Assassin\'s Creed II',
        desc_ru: 'Эпоха Возрождения, Италия. Эцио Аудиторе, молодой флорентийский аристократ, становится свидетелем казни своей семьи и отправляется в путь мести. Он узнаёт о тайном Братстве ассасинов и своём предназначении. Игра значительно расширила механику оригинала: добавилось управление экономикой, крафт, сражения на мечах и скрытый клинок. Эцио стал одним из самых любимых персонажей в истории игр.',
        desc_en: 'The Renaissance, Italy. Ezio Auditore, a young Florentine aristocrat, witnesses the execution of his family and embarks on a path of revenge. He learns about the secret Assassin Brotherhood and his destiny. The game significantly expanded the original mechanics: added economic management, crafting, sword fighting, and the hidden blade. Ezio became one of the most beloved characters in gaming history.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/33230/header.jpg',
        min: ['ОС: Windows XP/Vista/7', 'Процессор: Intel Core 2 Duo 1.8 GHz', 'ОЗУ: 1.5 GB', 'Видеокарта: GeForce 6800 / Radeon X1300', 'Место: 8 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core 2 Duo 2.6 GHz', 'ОЗУ: 2 GB', 'Видеокарта: GeForce 8800 / Radeon HD 4700', 'Место: 8 GB'],
        power_rank: 3,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Игра старая, пойдёт почти на всём.',
        doctor_advice_en: 'Old game, runs on almost anything.',
        year: 2009,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Stealth'],
        playtime_main: 19,
        playtime_completion: 32,
        metacritic: 86,
        steam: 'Очень положительные',
        ign: '9.2/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/_xkCPNECud8'
    },
    acb: {
        title_ru: 'Assassin\'s Creed: Brotherhood',
        title_en: 'Assassin\'s Creed: Brotherhood',
        desc_ru: 'Продолжение приключений Эцио в Риме. Эцио отправляется в Вечный город, чтобы сразиться с семьёй Борджиа и восстановить Братство ассасинов. Впервые в серии появилась возможность управлять отрядом ассасинов, вызывая их для помощи в бою или отправляя на миссии по всей Европе. Рим становится единым открытым миром, а не разделённым на районы.',
        desc_en: 'Continuation of Ezio\'s adventures in Rome. Ezio travels to the Eternal City to fight the Borgia family and restore the Assassin Brotherhood. For the first time in the series, you can command a squadron of assassins, calling them for help in battle or sending them on missions across Europe. Rome becomes a single open world, not divided into districts.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/48190/header.jpg',
        min: ['ОС: Windows XP/Vista/7', 'Процессор: Intel Core 2 Duo 1.8 GHz', 'ОЗУ: 1.5 GB', 'Видеокарта: GeForce 6800 / Radeon X1300', 'Место: 8 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core 2 Duo 2.6 GHz', 'ОЗУ: 2 GB', 'Видеокарта: GeForce 8800 / Radeon HD 4700', 'Место: 8 GB'],
        power_rank: 3,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Оптимизирована хорошо, проблем не будет.',
        doctor_advice_en: 'Well optimized, no problems.',
        year: 2010,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Stealth'],
        playtime_main: 16,
        playtime_completion: 30,
        metacritic: 88,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/zzNs4-kRLaE'
    },
    acr: {
        title_ru: 'Assassin\'s Creed: Revelations',
        title_en: 'Assassin\'s Creed: Revelations',
        desc_ru: 'Завершение истории Эцио и знакомство с Альтаиром. Постаревший Эцио отправляется в Константинополь, чтобы найти библиотеку Альтаира и узнать тайны Ордена. Игрок сможет играть за обоих легендарных ассасинов в разных временных периодах. Добавлены новые гаджеты: крюк-кошка для быстрого перемещения и бомбы разных типов.',
        desc_en: 'Conclusion of Ezio\'s story and introduction to Altaïr. An aging Ezio travels to Constantinople to find Altaïr\'s library and learn the Order\'s secrets. The player can play as both legendary assassins in different time periods. New gadgets added: the hook blade for fast movement and various types of bombs.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/201870/header.jpg',
        min: ['ОС: Windows XP/Vista/7', 'Процессор: Intel Core 2 Duo 1.8 GHz', 'ОЗУ: 1.5 GB', 'Видеокарта: GeForce 6800 / Radeon X1300', 'Место: 8 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core 2 Duo 2.6 GHz', 'ОЗУ: 2 GB', 'Видеокарта: GeForce 8800 / Radeon HD 4700', 'Место: 8 GB'],
        power_rank: 3,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Требования низкие.',
        doctor_advice_en: 'Low requirements.',
        year: 2011,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Stealth'],
        playtime_main: 14,
        playtime_completion: 28,
        metacritic: 80,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/HMsbMK9Odoc'
    },
    ac3: {
        title_ru: 'Assassin\'s Creed III',
        title_en: 'Assassin\'s Creed III',
        desc_ru: 'Американская революция, новый герой Коннор. Коннор, сын британца и индианки из племени могавков, вступает в борьбу за свободу колоний. Игра переносит действие в Америку XVIII века: Бостон, Нью-Йорк, Дикий Запад. Добавлена охота на диких животных, управление кораблём и масштабные битвы с участием сотен солдат.',
        desc_en: 'American Revolution, new hero Connor. Connor, son of a Briton and a Mohawk woman, joins the fight for colonial freedom. The game moves the action to 18th century America: Boston, New York, the Frontier. Added hunting wildlife, ship command, and large-scale battles with hundreds of soldiers.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/208480/header.jpg',
        min: ['ОС: Windows Vista/7', 'Процессор: Intel Core 2 Duo 2.6 GHz', 'ОЗУ: 2 GB', 'Видеокарта: GeForce 8800 GT / Radeon HD 4700', 'Место: 17 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core 2 Quad 2.7 GHz', 'ОЗУ: 4 GB', 'Видеокарта: GeForce GTX 260 / Radeon HD 5770', 'Место: 17 GB'],
        power_rank: 4,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Чуть более требовательная, чем предыдущие.',
        doctor_advice_en: 'Slightly more demanding than previous ones.',
        year: 2012,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Stealth'],
        playtime_main: 18,
        playtime_completion: 42,
        metacritic: 80,
        steam: 'Смешанные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1050 Ti',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/-pUhraVG7Ow'
    },
    ac4: {
        title_ru: 'Assassin\'s Creed IV: Black Flag',
        title_en: 'Assassin\'s Creed IV: Black Flag',
        desc_ru: 'Золотой век пиратства, Карибское море. Эдвард Кенуэй, отважный пират и охотник за сокровищами, попадает в конфликт между ассасинами и тамплиерами. Главная фишка игры — корабль "Галка", на котором можно бороздить Карибское море, грабить испанские галеоны, охотиться на китов и искать затонувшие сокровища. Один из лучших морских экшенов в истории.',
        desc_en: 'Golden Age of Piracy, Caribbean Sea. Edward Kenway, a brave pirate and treasure hunter, falls into the conflict between Assassins and Templars. The game\'s main feature is the ship "Jackdaw", which can sail the Caribbean, plunder Spanish galleons, hunt whales, and search for sunken treasure. One of the best naval action games in history.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/242050/header.jpg',
        min: ['ОС: Windows Vista/7', 'Процессор: Intel Core 2 Quad Q8400 / AMD Phenom II X4 940', 'ОЗУ: 2 GB', 'Видеокарта: Nvidia GeForce GTX 260 / AMD Radeon HD 4870', 'Место: 30 GB'],
        rec: ['ОС: Windows 7/8', 'Процессор: Intel Core i5 2400S / AMD FX 6100', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce GTX 560 Ti / AMD Radeon HD 7870', 'Место: 30 GB'],
        power_rank: 5,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Открытый мир требует больше ресурсов.',
        doctor_advice_en: 'Open world requires more resources.',
        year: 2013,
        developer: 'Ubisoft Montreal',
        genres: ['Action', 'Adventure', 'Pirates'],
        playtime_main: 22,
        playtime_completion: 60,
        metacritic: 83,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1650',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/OwVe4ZNeQZk'
    },
    acu: {
        title_ru: 'Assassin\'s Creed: Unity',
        title_en: 'Assassin\'s Creed: Unity',
        desc_ru: 'Французская революция, Париж. Арно Дориан, ассасин, пытается раскрыть заговор и спасти Францию от хаоса. Игра впервые в серии предлагает кооперативный режим для четырёх игроков. Париж воссоздан с невероятной детализацией — можно заходить в большинство зданий. Система паркура полностью переработана в сторону большей плавности и контроля.',
        desc_en: 'French Revolution, Paris. Arno Dorian, an Assassin, tries to uncover a conspiracy and save France from chaos. The game offers co-op mode for four players for the first time in the series. Paris is recreated with incredible detail — most buildings are enterable. The parkour system is completely redesigned for greater smoothness and control.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/289650/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-2500K / AMD FX-8350', 'ОЗУ: 6 GB', 'Видеокарта: Nvidia GeForce GTX 680 / AMD Radeon HD 7970', 'Место: 50 GB'],
        rec: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i7-3770 / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 780 / AMD Radeon R9 290X', 'Место: 50 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Известна проблемами с оптимизацией. Нужен мощный процессор.',
        doctor_advice_en: 'Known for optimization issues. Need a powerful CPU.',
        year: 2014,
        developer: 'Ubisoft',
        genres: ['Action', 'Stealth'],
        playtime_main: 18,
        playtime_completion: 45,
        metacritic: 70,
        steam: 'Смешанные',
        ign: '6.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/xzCEdSKMkdU'
    },
    acs: {
        title_ru: 'Assassin\'s Creed: Syndicate',
        title_en: 'Assassin\'s Creed: Syndicate',
        desc_ru: 'Викторианский Лондон, Индустриальная революция. Близнецы Джейкоб и Иви Фрай возглавляют борьбу уличных банд против тамплиеров, контролирующих город. Впервые в серии можно управлять двумя протагонистами с разными стилями игры. Добавлен крюк-кошка, позволяющий быстро перемещаться по крышам, и возможность управлять конными экипажами в гонках по улицам Лондона.',
        desc_en: 'Victorian London, Industrial Revolution. Twins Jacob and Evie Frye lead the fight of street gangs against the Templars controlling the city. For the first time in the series, you can control two protagonists with different playstyles. Added a rope launcher for quick roof travel and the ability to drive horse-drawn carriages in races through London streets.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/368500/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-2400 / AMD FX-6350', 'ОЗУ: 6 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon R9 270', 'Место: 50 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-3770 / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 760 / AMD Radeon R9 280X', 'Место: 50 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Оптимизация лучше, чем в Unity. Хорошо работает на средних настройках.',
        doctor_advice_en: 'Better optimization than Unity. Runs well on medium settings.',
        year: 2015,
        developer: 'Ubisoft Quebec',
        genres: ['Action', 'Stealth'],
        playtime_main: 20,
        playtime_completion: 50,
        metacritic: 74,
        steam: 'Очень положительные',
        ign: '8.2/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/WTBbwgsyxvg'
    },
    aco: {
        title_ru: 'Assassin\'s Creed: Origins',
        title_en: 'Assassin\'s Creed: Origins',
        desc_ru: 'Древний Египет, создание Братства ассасинов. Байек, последний защитник фараонов, отправляется в путешествие мести, которое приведёт к основанию Скрытых — предшественников ассасинов. Игра совершила поворот в сторону RPG: появились уровни, система прокачки, квесты, выбор оружия и способностей. Открытый мир Египта огромен и прекрасен — от пустынь до пирамид и оазисов.',
        desc_en: 'Ancient Egypt, creation of the Assassin Brotherhood. Bayek, the last protector of the pharaohs, embarks on a journey of revenge that leads to the founding of the Hidden Ones — the predecessors of the Assassins. The game shifted towards RPG: levels, progression system, quests, weapon choices, and abilities. Egypt\'s open world is huge and beautiful — from deserts to pyramids and oases.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582160/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-2400 / AMD FX-6350', 'ОЗУ: 6 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon R9 270', 'Место: 42 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-3770 / AMD Ryzen 5 1600', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 970 / AMD Radeon RX 480', 'Место: 42 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Хорошая оптимизация, но открытый мир нагружает процессор.',
        doctor_advice_en: 'Good optimization, but open world loads the CPU.',
        year: 2017,
        developer: 'Ubisoft',
        genres: ['Action', 'RPG'],
        playtime_main: 30,
        playtime_completion: 85,
        metacritic: 81,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 2060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/29y_UjW403c'
    },
    acod: {
        title_ru: 'Assassin\'s Creed: Odyssey',
        title_en: 'Assassin\'s Creed: Odyssey',
        desc_ru: 'Древняя Греция, эпоха Пелопоннесской войны. Вы выбираете одного из двух наёмников — Алексиоса или Кассандру — и отправляетесь в эпическое путешествие по Греции. Игра стала полноценной RPG с диалогами и выборами, влияющими на сюжет. Можно сражаться на суше и на море, участвовать в масштабных битвах и исследовать легендарные места — Афины, Спарту, Дельфы.',
        desc_en: 'Ancient Greece, the Peloponnesian War era. You choose one of two mercenaries — Alexios or Kassandra — and embark on an epic journey through Greece. The game became a full-fledged RPG with dialogues and choices affecting the story. You can fight on land and sea, participate in massive battles, and explore legendary locations — Athens, Sparta, Delphi.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/812140/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-2400 / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon R9 270X', 'Место: 46 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-3770 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 970 / AMD Radeon RX 570', 'Место: 46 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к процессору и видеокарте.',
        doctor_advice_en: 'Demanding on CPU and GPU.',
        year: 2018,
        developer: 'Ubisoft',
        genres: ['Action', 'RPG'],
        playtime_main: 45,
        playtime_completion: 145,
        metacritic: 83,
        steam: 'Очень положительные',
        ign: '9.2/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 2060 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/s_SJZSAtLBA'
    },
    acval: {
        title_ru: 'Assassin\'s Creed: Valhalla',
        title_en: 'Assassin\'s Creed: Valhalla',
        desc_ru: 'Эпоха викингов, завоевание Англии. Эйвор, бесстрашный воин-викинг, возглавляет свой клан в поисках нового дома. Им предстоит сражаться с англосаксонскими королевствами, заключать союзы и строить своё поселение. Система сражений переработана: теперь можно использовать два оружия одновременно. Добавлены рейды на монастыри и возможность развивать собственное поселение.',
        desc_en: 'Viking age, conquest of England. Eivor, a fearless Viking warrior, leads their clan in search of a new home. They must fight the Anglo-Saxon kingdoms, forge alliances, and build their settlement. The combat system is redesigned: you can now dual-wield weapons. Added monastery raids and the ability to develop your own settlement.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2208920/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-4460 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 960 / AMD Radeon R9 380', 'Место: 130 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-6700 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1060 / AMD Radeon RX 5700', 'Место: 130 GB'],
        power_rank: 8,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Очень требовательна, особенно к видеокарте.',
        doctor_advice_en: 'Very demanding, especially on GPU.',
        year: 2020,
        developer: 'Ubisoft',
        genres: ['Action', 'RPG'],
        playtime_main: 60,
        playtime_completion: 145,
        metacritic: 80,
        steam: 'Смешанные',
        ign: '8/10',
        build: {
            cpu: 'Intel Core i5-12400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/ssrNcwxALS4'
    },
    // Far Cry
    fc1: {
        title_ru: 'Far Cry',
        title_en: 'Far Cry',
        desc_ru: 'Начало легендарной серии. Джек Карвер, бывший спецназовец, нанимается для сопровождения журналистки на тропический остров. Всё идет не по плану, и Джеку приходится сражаться с наёмниками и мутантами. Игра поражала графикой на момент выхода — огромные открытые пространства, детализированная растительность и вода. Задала стандарты шутеров на годы вперёд.',
        desc_en: 'The beginning of the legendary series. Jack Carver, a former Special Forces soldier, is hired to escort a journalist to a tropical island. Everything goes wrong, and Jack must fight mercenaries and mutants. The game amazed with its graphics at release — huge open spaces, detailed vegetation, and water. Set standards for shooters for years to come.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/13520/header.jpg',
        min: ['ОС: Windows 2000/XP', 'Процессор: Pentium III 1 GHz / Athlon', 'ОЗУ: 256 MB', 'Видеокарта: 64 MB VRAM', 'Место: 4 GB'],
        rec: ['ОС: Windows 2000/XP', 'Процессор: Pentium 4 2 GHz', 'ОЗУ: 512-1024 MB', 'Видеокарта: 128 MB VRAM', 'Место: 4 GB'],
        power_rank: 2,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Очень старая игра, пойдёт на любом компьютере.',
        doctor_advice_en: 'Very old game, runs on any computer.',
        year: 2004,
        developer: 'Crytek',
        genres: ['Shooter'],
        playtime_main: 12,
        playtime_completion: 20,
        metacritic: 79,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/AYh2w6kK1W4'
    },
    fc2: {
        title_ru: 'Far Cry 2',
        title_en: 'Far Cry 2',
        desc_ru: 'Действие переносится в вымышленную африканскую страну, охваченную гражданской войной. Игрок — наёмник, которому поручено убить "Пальму". Инновационная для своего времени система: малярия, оружие, которое заклинивает и ржавеет, динамические пожары, распространяющиеся по траве. Атмосфера безысходности и жестокости войны.',
        desc_en: 'The action moves to a fictional African country torn by civil war. The player is a mercenary tasked with killing "The Jackal". Innovative systems for its time: malaria, weapons that jam and rust, dynamic fires spreading through grass. An atmosphere of hopelessness and the brutality of war.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/19900/header.jpg',
        min: ['ОС: Windows XP/Vista', 'Процессор: Pentium 4 3.2 GHz / Athlon 64 3200+', 'ОЗУ: 1 GB', 'Видеокарта: 256 MB VRAM', 'Место: 4 GB'],
        rec: ['ОС: Windows XP/Vista', 'Процессор: Core 2 Duo / Athlon 64 X2', 'ОЗУ: 2 GB', 'Видеокарта: 512 MB VRAM', 'Место: 4 GB'],
        power_rank: 3,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Работает на любом современном ПК.',
        doctor_advice_en: 'Runs on any modern PC.',
        year: 2008,
        developer: 'Ubisoft Montreal',
        genres: ['Shooter'],
        playtime_main: 20,
        playtime_completion: 35,
        metacritic: 79,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/FCeEvQ68jY8'
    },
    fc3: {
        title_ru: 'Far Cry 3',
        title_en: 'Far Cry 3',
        desc_ru: 'Тропический остров, безумный Ваас, становление воина. Джейсон Броди, обычный турист, оказывается в плену у пиратов. Ему предстоит превратиться из изнеженного горожанина в безжалостного воина, чтобы спасти своих друзей. Культовый антагонист Ваас Монтенегро и система прокачки персонажа сделали эту часть легендарной.',
        desc_en: 'Tropical island, crazy Vaas, becoming a warrior. Jason Brody, an ordinary tourist, is captured by pirates. He must transform from a spoiled city dweller into a ruthless warrior to save his friends. The iconic antagonist Vaas Montenegro and the character progression system made this part legendary.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/220240/header.jpg',
        min: ['ОС: Windows XP/Vista/7', 'Процессор: Intel Core 2 Duo E6700 / AMD Athlon64 X2 6000+', 'ОЗУ: 2 GB', 'Видеокарта: Nvidia GeForce 8800 GTX / AMD Radeon HD 2900 XT', 'Место: 15 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core i3-530 / AMD Phenom II X2 565', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce GTX 460 / AMD Radeon HD 5770', 'Место: 15 GB'],
        power_rank: 4,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Классика, работает на любом современном ПК.',
        doctor_advice_en: 'Classic, runs on any modern PC.',
        year: 2012,
        developer: 'Ubisoft Montreal',
        genres: ['Shooter', 'Open world'],
        playtime_main: 16,
        playtime_completion: 40,
        metacritic: 88,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1050 Ti',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/J6gnOVJsCsM'
    },
    fc4: {
        title_ru: 'Far Cry 4',
        title_en: 'Far Cry 4',
        desc_ru: 'Гималаи, диктатор Паган Мин, свобода. Аджей Гейл возвращается на родину в Кират, чтобы развеять прах матери, но оказывается втянут в гражданскую войну против безумного диктатора. Добавлен вертолёт и возможность сбрасывать припасы союзникам. Открытый мир Гималаев впечатляет вертикальностью — горы, ущелья, буддийские монастыри.',
        desc_en: 'Himalayas, dictator Pagan Min, freedom. Ajay Ghale returns to his homeland of Kyrat to scatter his mother\'s ashes but is drawn into a civil war against a mad dictator. Added helicopters and the ability to drop supplies to allies. The Himalayan open world impresses with its verticality — mountains, gorges, Buddhist monasteries.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/298110/header.jpg',
        min: ['ОС: Windows 7/8', 'Процессор: Intel Core i5-750 / AMD Phenom II X4 955', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce GTX 460 / AMD Radeon HD 5850', 'Место: 30 GB'],
        rec: ['ОС: Windows 7/8', 'Процессор: Intel Core i5-2400S / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 680 / AMD Radeon R9 290X', 'Место: 30 GB'],
        power_rank: 5,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: true,
        doctor_advice_ru: 'Хорошо оптимизирована, но горы могут нагружать CPU.',
        doctor_advice_en: 'Well optimized, but mountains can load CPU.',
        year: 2014,
        developer: 'Ubisoft Montreal',
        genres: ['Shooter', 'Open world'],
        playtime_main: 20,
        playtime_completion: 50,
        metacritic: 80,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1650 Super',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/R50TTkjHX80'
    },
    fc5: {
        title_ru: 'Far Cry 5',
        title_en: 'Far Cry 5',
        desc_ru: 'Монтана, секта, открытый мир и хаос. Округ Хоуп-Каунти захвачен фанатиками из секты "Врата Эдема". Игрок — помощник шерифа, который пытается освободить жителей. Впервые в серии нет вышки для активации карты — всё открывается исследованием. Добавлена система найма союзников и возможность летать на самолётах.',
        desc_en: 'Montana, cult, open world and chaos. Hope County is taken over by fanatics from the "Eden\'s Gate" cult. The player is a deputy sheriff trying to free the residents. For the first time in the series, there are no towers to activate the map — everything opens through exploration. Added a companion system and the ability to fly planes.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/552520/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-2400 / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 670 / AMD R9 270', 'Место: 40 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4770 / AMD Ryzen 5 1600', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 970 / AMD R9 290X', 'Место: 40 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к видеопамяти.',
        doctor_advice_en: 'Demanding on VRAM.',
        year: 2018,
        developer: 'Ubisoft',
        genres: ['Shooter', 'Open world'],
        playtime_main: 23,
        playtime_completion: 55,
        metacritic: 78,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/Kdaoe4hbMso'
    },
    fcnd: {
        title_ru: 'Far Cry: New Dawn',
        title_en: 'Far Cry: New Dawn',
        desc_ru: 'Продолжение Far Cry 5, действие происходит через 17 лет после ядерной войны. Мир изменился, природа возродилась в ярких красках, но выжившие борются за ресурсы. Игроки защищают поселение от бандитов-близнецов. Добавлены RPG-элементы: уровни оружия, база с улучшениями и рейды на вражеские крепости.',
        desc_en: 'A continuation of Far Cry 5, set 17 years after a nuclear war. The world has changed, nature has revived in bright colors, but survivors fight for resources. Players defend a settlement from twin bandits. Added RPG elements: weapon levels, base upgrades, and raids on enemy strongholds.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/939960/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-2400 / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 670 / AMD R9 270', 'Место: 30 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4770 / AMD Ryzen 5 1600', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 970 / AMD R9 290X', 'Место: 30 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Оптимизация схожа с Far Cry 5.',
        doctor_advice_en: 'Optimization similar to Far Cry 5.',
        year: 2019,
        developer: 'Ubisoft',
        genres: ['Shooter'],
        playtime_main: 12,
        playtime_completion: 30,
        metacritic: 72,
        steam: 'Смешанные',
        ign: '7.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/6eLHk2Eug78'
    },
    fcprimal: {
        title_ru: 'Far Cry Primal',
        title_en: 'Far Cry Primal',
        desc_ru: 'Каменный век, саблезубые тигры, выживание. Действие происходит в 10 000 году до н.э. Таккар, охотник из племени Вен, пытается спасти свой народ и объединить племена против врагов. Вместо огнестрельного оружия — копья, луки и прирученные звери. Можно приручать саблезубых тигров, медведей и сов для разведки.',
        desc_en: 'Stone Age, sabre-toothed tigers, survival. Set in 10,000 BCE. Takkar, a hunter from the Wenja tribe, tries to save his people and unite tribes against enemies. Instead of firearms — spears, bows, and tamed beasts. You can tame sabre-toothed tigers, bears, and owls for reconnaissance.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/371660/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i3-550 / AMD Phenom II X4 955', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce GTX 460 / AMD Radeon HD 5770', 'Место: 20 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-2600K / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 780 / AMD Radeon R9 280X', 'Место: 20 GB'],
        power_rank: 5,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: false,
        doctor_advice_ru: 'Оптимизирована, но огонь и дым могут нагружать GPU.',
        doctor_advice_en: 'Optimized, but fire and smoke can load GPU.',
        year: 2016,
        developer: 'Ubisoft',
        genres: ['Action', 'Survival'],
        playtime_main: 15,
        playtime_completion: 35,
        metacritic: 74,
        steam: 'Очень положительные',
        ign: '7.9/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1050 Ti',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/mH89uPo_7Ng'
    },
    fc6: {
        title_ru: 'Far Cry 6',
        title_en: 'Far Cry 6',
        desc_ru: 'Куба, партизаны, Антон Кастильо. Яра, тропический рай под властью диктатора Антона Кастильо. Игрок — местный житель, вступающий в партизанское сопротивление. Антона играет Джанкарло Эспозито. Добавлены новые типы оружия, включая самодельные "Resolver weapons", и возможность управлять танками и лошадьми.',
        desc_en: 'Cuba, guerrillas, Anton Castillo. Yara, a tropical paradise under the rule of dictator Anton Castillo. The player is a local resident joining the guerrilla resistance. Anton is played by Giancarlo Esposito. Added new weapon types, including homemade "Resolver weapons", and the ability to drive tanks and horses.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2369390/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-4460 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 960 / AMD Radeon R9 380', 'Место: 60 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-7700 / AMD Ryzen 5 2600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1080 / AMD Radeon RX 5700 XT', 'Место: 60 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Современная часть, требует мощную видеокарту.',
        doctor_advice_en: 'Modern part, requires a powerful GPU.',
        year: 2021,
        developer: 'Ubisoft',
        genres: ['Shooter'],
        playtime_main: 22,
        playtime_completion: 55,
        metacritic: 72,
        steam: 'Смешанные',
        ign: '8/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/-IJuKT1mHO8'
    },
    // God of War
    gow2018: {
        title_ru: 'God of War (2018)',
        title_en: 'God of War (2018)',
        desc_ru: 'Кратос и его сын Атрей в мире скандинавской мифологии. После смерти второй жены Кратос отправляется с сыном в путешествие, чтобы развеять её прах с высочайшей вершины. Их путь полон опасностей — монстры, боги и собственные демоны. Переосмысление серии: камера с плеча, топор Левиафан вместо клинков Хаоса, более глубокий и эмоциональный сюжет.',
        desc_en: 'Kratos and his son Atreus in the world of Norse mythology. After the death of his second wife, Kratos embarks on a journey with his son to scatter her ashes from the highest peak. Their path is full of dangers — monsters, gods, and their own demons. A reimagining of the series: over-the-shoulder camera, Leviathan axe instead of the Blades of Chaos, a deeper and more emotional story.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-2500K / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 960 / AMD Radeon R9 290X', 'Место: 70 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4770K / AMD Ryzen 7 2700', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1060 / AMD Radeon RX 580', 'Место: 70 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Отличный порт, но требует не менее 6 ГБ VRAM.',
        doctor_advice_en: 'Great port, but requires at least 6GB VRAM.',
        year: 2018,
        developer: 'Santa Monica Studio',
        genres: ['Action', 'Adventure'],
        playtime_main: 22,
        playtime_completion: 52,
        metacritic: 94,
        steam: 'Очень положительные',
        ign: '10/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 2060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/e5dFIKAPxhU'
    },
    gowrag: {
        title_ru: 'God of War: Ragnarök',
        title_en: 'God of War: Ragnarök',
        desc_ru: 'Продолжение саги, финал скандинавской истории. Кратос и Атрей готовятся к Рагнарёку — гибели богов. Атрей вырос и ищет ответы о своей судьбе, а Кратос пытается защитить сына и принять своё прошлое. Добавлены новые способности, оружие и огромные локации — девять миров скандинавской мифологии, включая Ванахейм и Свартальфахейм.',
        desc_en: 'Continuation of the saga, the finale of the Norse story. Kratos and Atreus prepare for Ragnarök — the death of the gods. Atreus has grown and seeks answers about his destiny, while Kratos tries to protect his son and accept his past. Added new abilities, weapons, and huge locations — the nine realms of Norse mythology, including Vanaheim and Svartalfheim.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-6600K / AMD Ryzen 5 2600', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 1060 / AMD Radeon RX 580', 'Место: 90 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-7700K / AMD Ryzen 7 3700X', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 2060 SUPER / AMD Radeon RX 5700 XT', 'Место: 90 GB'],
        power_rank: 8,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Очень требовательна, нужна современная видеокарта.',
        doctor_advice_en: 'Very demanding, need a modern GPU.',
        year: 2022,
        developer: 'Santa Monica Studio',
        genres: ['Action', 'Adventure'],
        playtime_main: 26,
        playtime_completion: 58,
        metacritic: 94,
        steam: 'Очень положительные',
        ign: '10/10',
        build: {
            cpu: 'Intel Core i5-12400F',
            gpu: 'NVIDIA RTX 3060 Ti',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/V0aZ-mTNKo8'
    },
    // Hitman
    hitman2: {
        title_ru: 'Hitman 2',
        title_en: 'Hitman 2',
        desc_ru: 'Агент 47, глобальные заговоры, стелс-экшен. Продолжение перезапуска серии. 47 путешествует по миру, выполняя контракты и раскрывая тайны своего прошлого. Локации-песочницы: Майами, Колумбия, Мумбаи и другие. Каждая миссия предлагает множество способов достижения цели — от снайперской винтовки до отравления в толпе.',
        desc_en: 'Agent 47, global conspiracies, stealth action. Continuation of the series reboot. 47 travels the world, completing contracts and uncovering secrets of his past. Sandbox locations: Miami, Colombia, Mumbai, and more. Each mission offers multiple ways to achieve the goal — from sniper rifles to poisoning in a crowd.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/863550/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-2500K / AMD FX-8100', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 60 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-3770 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1070 / AMD Radeon RX 5700', 'Место: 60 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Хорошо оптимизирована, любит многоядерные процессоры.',
        doctor_advice_en: 'Well optimized, likes multi-core CPUs.',
        year: 2018,
        developer: 'IO Interactive',
        genres: ['Stealth'],
        playtime_main: 10,
        playtime_completion: 45,
        metacritic: 82,
        steam: 'Очень положительные',
        ign: '8.7/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/hAd8QdsUMOo'
    },
    hitman3: {
        title_ru: 'Hitman 3',
        title_en: 'Hitman 3',
        desc_ru: 'Завершение трилогии, новые локации. Финал истории, начатой в Hitman 2016. 47 выполняет последние контракты в Дубае, Дартмуре, Берлине, Чунцине и Аргентине. Игра объединяет все локации из предыдущих частей в едином лаунчере. Добавлены новые механики: фотоаппарат для разведки и возможность переносить оружие в кейсе.',
        desc_en: 'Conclusion of the trilogy, new locations. The finale of the story that began in Hitman 2016. 47 completes his final contracts in Dubai, Dartmoor, Berlin, Chongqing, and Argentina. The game unites all locations from previous parts in a single launcher. Added new mechanics: a camera for reconnaissance and the ability to carry weapons in a briefcase.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-2500K / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 60 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4790 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1070 / AMD Radeon RX 5700', 'Место: 60 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требования аналогичны Hitman 2.',
        doctor_advice_en: 'Requirements similar to Hitman 2.',
        year: 2021,
        developer: 'IO Interactive',
        genres: ['Stealth'],
        playtime_main: 8,
        playtime_completion: 40,
        metacritic: 84,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/WB2BSbaRmgY'
    },
    // Battlefield
    bf3: {
        title_ru: 'Battlefield 3',
        title_en: 'Battlefield 3',
        desc_ru: 'Современный шутер, масштабные сражения. DICE вернула серию к современным войнам после Vietnam. Кампания рассказывает о группе морпехов, расследующих ядерную угрозу. Мультиплеер стал эталоном: огромные карты, разрушаемость, техника от танков до истребителей. Система Frostbite 2.0 поражала графикой.',
        desc_en: 'Modern shooter, large-scale battles. DICE returned the series to modern warfare after Vietnam. The campaign follows a group of Marines investigating a nuclear threat. Multiplayer became the benchmark: huge maps, destructibility, vehicles from tanks to fighters. The Frostbite 2.0 engine amazed with graphics.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238820/header.jpg',
        min: ['ОС: Windows 7', 'Процессор: Intel Core 2 Duo 2.4 GHz', 'ОЗУ: 2 GB', 'Видеокарта: Nvidia GeForce 8800 GT / AMD Radeon HD 3870', 'Место: 20 GB'],
        rec: ['ОС: Windows 7', 'Процессор: Intel Core 2 Quad 2.8 GHz', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce GTX 560 / AMD Radeon HD 6950', 'Место: 20 GB'],
        power_rank: 4,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Старая игра, пойдёт на любом современном ПК.',
        doctor_advice_en: 'Old game, runs on any modern PC.',
        year: 2011,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: 6,
        playtime_completion: 15,
        metacritic: 84,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1050 Ti',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/2zw8SmsDfN4'
    },
    bf4: {
        title_ru: 'Battlefield 4',
        title_en: 'Battlefield 4',
        desc_ru: 'Продолжение, разрушаемость, мультиплеер. Действие разворачивается в 2020 году во время войны между США, Россией и Китаем. Кампания получила более проработанный сюжет, но главное — мультиплеер с огромными картами, Левелейшн (разрушаемость небоскрёбов) и морскими сражениями. До сих пор активное комьюнити.',
        desc_en: 'Sequel, destructibility, multiplayer. Set in 2020 during a war between the US, Russia, and China. The campaign had a more developed story, but the main focus is multiplayer with huge maps, Levolution (skyscraper destruction), and naval battles. Still has an active community.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238860/header.jpg',
        min: ['ОС: Windows 7/8', 'Процессор: Intel Core 2 Duo 2.4 GHz', 'ОЗУ: 4 GB', 'Видеокарта: Nvidia GeForce 8800 GT / AMD Radeon HD 3870', 'Место: 30 GB'],
        rec: ['ОС: Windows 7/8', 'Процессор: Intel Core i5-3470 / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 30 GB'],
        power_rank: 5,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: false,
        doctor_advice_ru: 'Хорошо работает на средних ПК.',
        doctor_advice_en: 'Works well on mid-range PCs.',
        year: 2013,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: 7,
        playtime_completion: 20,
        metacritic: 81,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GTX 1650 Super',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/hl-VV9loYLw'  // новый трейлер для BF4
    },
    bf1: {
        title_ru: 'Battlefield 1',
        title_en: 'Battlefield 1',
        desc_ru: 'Первая мировая война, атмосфера, техника. DICE обратилась к истокам войн XX века. Кампания состоит из нескольких историй солдат разных стран. Мультиплеер предлагает сражения на винтовках, пулемётах, с использованием конницы, танков и бипланов. Атмосфера ужаса и величия войны передана потрясающе.',
        desc_en: 'World War I, atmosphere, vehicles. DICE turned to the origins of 20th century warfare. The campaign consists of several stories of soldiers from different countries. Multiplayer offers battles with rifles, machine guns, using cavalry, tanks, and biplanes. The atmosphere of horror and grandeur of war is conveyed stunningly.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-6600K / AMD FX-6350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7850', 'Место: 50 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4790 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1060 / AMD Radeon RX 480', 'Место: 50 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к процессору в мультиплеере.',
        doctor_advice_en: 'Demanding on CPU in multiplayer.',
        year: 2016,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: 7,
        playtime_completion: 25,
        metacritic: 87,
        steam: 'Очень положительные',
        ign: '9/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/c7nRTF2SowQ'  // новый трейлер для BF1
    },
    bfv: {
        title_ru: 'Battlefield V',
        title_en: 'Battlefield V',
        desc_ru: 'Вторая мировая, новые режимы. Вернулись к истокам WW2, но с необычных ракурсов — норвежское сопротивление, французские колониальные войска. Добавлена система строительства укреплений и новые режимы, включая королевскую битву Firestorm. Физика и графика на высоте.',
        desc_en: 'World War II, new modes. Returned to WW2 roots, but from unusual perspectives — Norwegian resistance, French colonial troops. Added a fortification building system and new modes, including the Firestorm battle royale. Physics and graphics are top-notch.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238810/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-6600K / AMD FX-8350', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7850', 'Место: 50 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4790 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1060 / AMD Radeon RX 580', 'Место: 50 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Аналогично BF1.',
        doctor_advice_en: 'Similar to BF1.',
        year: 2018,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: 6,
        playtime_completion: 20,
        metacritic: 73,
        steam: 'Смешанные',
        ign: '7.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/fb1MR85XFOc'  // новый трейлер для BFV
    },
    bf2042: {
        title_ru: 'Battlefield 2042',
        title_en: 'Battlefield 2042',
        desc_ru: 'Будущее, огромные карты, техника. Действие в 2042 году, когда климатические катастрофы уничтожили привычный мир. Только мультиплеер, 128 игроков на ПК, система специалистов вместо классов, ураганы и торнадо на картах. Игра получила множество обновлений и сейчас находится в хорошем состоянии.',
        desc_en: 'Future, huge maps, vehicles. Set in 2042, when climate disasters have destroyed the familiar world. Multiplayer only, 128 players on PC, specialist system instead of classes, hurricanes and tornadoes on maps. The game received numerous updates and is now in good shape.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1517290/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-6600K / AMD Ryzen 5 1600', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 1050 Ti / AMD Radeon RX 560', 'Место: 100 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4790 / AMD Ryzen 7 2700X', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 3060 / AMD Radeon RX 6600 XT', 'Место: 100 GB'],
        power_rank: 8,
        rtx_supported: true,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Очень требовательна, особенно к видеокарте.',
        doctor_advice_en: 'Very demanding, especially on GPU.',
        year: 2021,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: null,
        playtime_completion: null,
        metacritic: 68,
        steam: 'Смешанные',
        ign: '6/10',
        build: {
            cpu: 'Intel Core i5-12400F',
            gpu: 'NVIDIA RTX 3060 Ti',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/ASzOzrB-a9E'  // новый трейлер для BF2042 (был и раньше, но оставим)
    },
    bf6: {
        title_ru: 'Battlefield 6',
        title_en: 'Battlefield 6',
        desc_ru: 'Новая часть легендарной серии, действие разворачивается в современном мире. Разработчики обещают возвращение к классическим классам, разрушаемость нового уровня и масштабные сражения на 128 игроков. Релиз запланирован на 10 октября 2025 года. Игра использует новейшую версию движка Frostbite.',
        desc_en: 'A new installment of the legendary series, set in the modern world. Developers promise a return to classic classes, a new level of destructibility, and large-scale battles with 128 players. Release is scheduled for October 10, 2025. The game uses the latest version of the Frostbite engine.',
        image: 'https://avatars.mds.yandex.net/get-mpic/15049620/2a000001986a58ebf4d46501390ab7cd1fcd/orig',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-8400 / AMD Ryzen 5 2600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 2060 / AMD Radeon RX 5600 XT (6GB VRAM)', 'Место: 55 GB HDD'],
        rec: ['ОС: Windows 11 64-bit', 'Процессор: Intel Core i7-10700 / AMD Ryzen 7 3700X', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce RTX 3060 Ti / AMD Radeon RX 6700 XT', 'Место: 80 GB SSD'],
        power_rank: 8,
        rtx_supported: true,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Новая часть, требует современное железо для высоких настроек. SSD рекомендуется.',
        doctor_advice_en: 'New installment, requires modern hardware for high settings. SSD recommended.',
        year: 2025,
        developer: 'DICE',
        genres: ['Shooter'],
        playtime_main: null,
        playtime_completion: null,
        metacritic: null,
        steam: null,
        ign: null,
        build: {
            cpu: 'Intel Core i5-13600K',
            gpu: 'NVIDIA RTX 4070',
            ram: 32
        },
        trailer: 'https://www.youtube.com/embed/example' // замени, когда выйдет
    },
    // Forza Horizon
    fh3: {
        title_ru: 'Forza Horizon 3',
        title_en: 'Forza Horizon 3',
        desc_ru: 'Третья часть серии, действие переносится в Австралию. Игрок становится организатором фестиваля Horizon. Огромный открытый мир: джунгли, пустыни, города и побережья. Добавлены внедорожники, багги и возможность создавать собственные чемпионаты.',
        desc_en: 'The third part of the series, set in Australia. The player becomes the festival organizer. Huge open world: jungles, deserts, cities, and coastlines. Added off-road vehicles, buggies, and the ability to create your own championships.',
        image: 'https://avatars.mds.yandex.net/get-entity_search/5396454/1243827245/S600xU_2x',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-4460 / AMD FX-6350', 'ОЗУ: 8 GB', 'Видеокарта: NVIDIA GeForce GTX 760 / AMD Radeon R7 260X', 'Место: 65 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-6700 / AMD Ryzen 5 1600', 'ОЗУ: 12 GB', 'Видеокарта: NVIDIA GeForce GTX 1060 / AMD Radeon RX 480', 'Место: 65 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требования аналогичны Horizon 2, но мир больше.',
        doctor_advice_en: 'Requirements similar to Horizon 2, but the world is larger.',
        year: 2016,
        developer: 'Playground Games',
        genres: ['Racing'],
        playtime_main: 15,
        playtime_completion: 40,
        metacritic: 91,
        steam: 'Очень положительные',
        ign: '9.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/RqkpT0qag5c'  // новый трейлер FH3
    },
    fh4: {
        title_ru: 'Forza Horizon 4',
        title_en: 'Forza Horizon 4',
        desc_ru: 'Действие происходит в Великобритании. Главная особенность — смена времён года, которые меняют ландшафт и геймплей. Зимой озёра замерзают, открывая новые маршруты, осенью листва устилает дороги. Огромный выбор автомобилей и постоянные онлайн-события.',
        desc_en: 'Set in Great Britain. The main feature is the changing seasons, which alter the landscape and gameplay. In winter, lakes freeze, opening new routes; in autumn, leaves cover the roads. Huge selection of cars and constant online events.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1293830/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-4460 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: NVIDIA GeForce GTX 970 / AMD Radeon RX 470', 'Место: 80 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-6700 / AMD Ryzen 5 1600', 'ОЗУ: 12 GB', 'Видеокарта: NVIDIA GeForce GTX 1070 / AMD Radeon RX Vega 64', 'Место: 80 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к видеокарте из-за смены сезонов.',
        doctor_advice_en: 'Demanding on GPU due to season changes.',
        year: 2018,
        developer: 'Playground Games',
        genres: ['Racing'],
        playtime_main: 20,
        playtime_completion: 50,
        metacritic: 92,
        steam: 'Очень положительные',
        ign: '9.6/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA RTX 2060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/5xy4n73WOMM'// новый трейлер FH4
    },
    fh5: {
        title_ru: 'Forza Horizon 5',
        title_en: 'Forza Horizon 5',
        desc_ru: 'Действие происходит в Мексике. Самый большой открытый мир в серии с разнообразными биомами: пустыни, джунгли, пляжи, города и вулканы. Улучшенная графика, физика и система тюнинга. Постоянные обновления и живые события.',
        desc_en: 'Set in Mexico. The largest open world in the series with diverse biomes: deserts, jungles, beaches, cities, and volcanoes. Improved graphics, physics, and tuning system. Constant updates and live events.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
        min: ['ОС: Windows 10', 'Процессор: Intel Core i5-4460 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: NVIDIA GeForce GTX 970 / AMD Radeon RX 470', 'Место: 110 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-10700 / AMD Ryzen 5 3600', 'ОЗУ: 16 GB', 'Видеокарта: NVIDIA GeForce RTX 2070 / AMD Radeon RX 6800', 'Место: 110 GB'],
        power_rank: 7,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Очень требовательна, особенно к видеокарте на высоких настройках.',
        doctor_advice_en: 'Very demanding, especially on GPU at high settings.',
        year: 2021,
        developer: 'Playground Games',
        genres: ['Racing'],
        playtime_main: 22,
        playtime_completion: 55,
        metacritic: 92,
        steam: 'Очень положительные',
        ign: '10/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/FYH9n37B7Yw'  // новый трейлер FH5
    },
    // Симуляторы
    assettocorsa: {
        title_ru: 'Assetto Corsa',
        title_en: 'Assetto Corsa',
        desc_ru: 'Реалистичный автосимулятор, ориентированный на трек-дни и гоночные трассы. Известен своей точной физикой, поддержкой модов и огромным комьюнити. Включает множество лицензированных автомобилей и трасс. Идеально подходит для любителей симуляции и виртуальных гонок.',
        desc_en: 'A realistic racing simulator focused on track days and racing circuits. Known for its accurate physics, mod support, and huge community. Includes many licensed cars and tracks. Perfect for simulation enthusiasts and virtual racing.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/244210/header.jpg',
        min: ['ОС: Windows 7/8/10', 'Процессор: Intel Core i5-4460 / AMD FX-6300', 'ОЗУ: 6 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 50 GB'],
        rec: ['ОС: Windows 10', 'Процессор: Intel Core i7-4790 / AMD Ryzen 5 1600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 970 / AMD Radeon RX 580', 'Место: 50 GB'],
        power_rank: 6,
        rtx_supported: false,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Хорошо оптимизирована, но с модами может требоваться больше ресурсов.',
        doctor_advice_en: 'Well optimized, but with mods may require more resources.',
        year: 2014,
        developer: 'Kunos Simulazioni',
        genres: ['Racing', 'Simulator'],
        playtime_main: 15,
        playtime_completion: 50,
        metacritic: 83,
        steam: 'Очень положительные',
        ign: '8.5/10',
        build: {
            cpu: 'Intel Core i5-10400F',
            gpu: 'NVIDIA GTX 1660 Super',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/TDFN-E30jhU'
    },
    accomp: {
        title_ru: 'Assetto Corsa Competizione',
        title_en: 'Assetto Corsa Competizione',
        desc_ru: 'Официальный симулятор чемпионата GT World Challenge. Сфокусирован на гонках класса GT3 и GT4. Невероятно реалистичная физика, динамическая смена погоды, 24-часовой цикл и поддержка VR. Лучший выбор для любителей GT-гонок.',
        desc_en: 'The official GT World Challenge simulator. Focused on GT3 and GT4 class racing. Incredibly realistic physics, dynamic weather, 24-hour cycle, and VR support. The best choice for GT racing enthusiasts.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/805550/header.jpg',
        min: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-4460 / AMD FX-6300', 'ОЗУ: 8 GB', 'Видеокарта: Nvidia GeForce GTX 660 / AMD Radeon HD 7870', 'Место: 50 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i7-6700 / AMD Ryzen 5 2600', 'ОЗУ: 16 GB', 'Видеокарта: Nvidia GeForce GTX 1070 / AMD Radeon RX 580', 'Место: 50 GB SSD'],
        power_rank: 7,
        rtx_supported: true,
        cpu_intensive: true,
        gpu_intensive: true,
        doctor_advice_ru: 'Требовательна к процессору и видеокарте. Рекомендуется SSD.',
        doctor_advice_en: 'Demanding on CPU and GPU. SSD recommended.',
        year: 2018,
        developer: 'Kunos Simulazioni',
        genres: ['Racing', 'Simulator'],
        playtime_main: 20,
        playtime_completion: 60,
        metacritic: 82,
        steam: 'Очень положительные',
        ign: '8.8/10',
        build: {
            cpu: 'Intel Core i5-11400F',
            gpu: 'NVIDIA RTX 3060',
            ram: 16
        },
        trailer: 'https://www.youtube.com/embed/CYncAnd31Q8'
    },
    ets2: {
        title_ru: 'Euro Truck Simulator 2',
        title_en: 'Euro Truck Simulator 2',
        desc_ru: 'Стань королём европейских дорог! Управляй грузовиком, выполняй заказы, расширяй автопарк, нанимай водителей и строй свою транспортную империю. Огромная карта Европы с регулярными обновлениями, поддержка модов и реалистичная физика.',
        desc_en: 'Become the king of European roads! Drive a truck, complete orders, expand your fleet, hire drivers and build your transport empire. Huge map of Europe with regular updates, mod support and realistic physics.',
        image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg',
        min: ['ОС: Windows 7 64-bit', 'Процессор: Intel Core 2 Duo 2.4 GHz / AMD Athlon 64 X2 2.8 GHz', 'ОЗУ: 4 GB', 'Видеокарта: GeForce 8600 GT / Radeon HD 2600 XT', 'Место: 12 GB'],
        rec: ['ОС: Windows 10 64-bit', 'Процессор: Intel Core i5-6400 / AMD Ryzen 3 1200', 'ОЗУ: 8 GB', 'Видеокарта: GeForce GTX 760 / Radeon HD 7870', 'Место: 25 GB (с DLC)'],
        power_rank: 4,
        rtx_supported: false,
        cpu_intensive: false,
        gpu_intensive: false,
        doctor_advice_ru: 'Игра нетребовательная, но с кучей DLC и модами может загружать процессор. SSD ускорит загрузку.',
        doctor_advice_en: 'The game is not demanding, but with lots of DLC and mods it can load the CPU. SSD speeds up loading.',
        year: 2012,
        developer: 'SCS Software',
        genres: ['Simulator', 'Racing'],
        playtime_main: 50,
        playtime_completion: 300,
        metacritic: 79,
        steam: 'Очень положительные',
        ign: '8/10',
        build: {
            cpu: 'Intel Core i3-10100F',
            gpu: 'NVIDIA GT 1030',
            ram: 8
        },
        trailer: 'https://www.youtube.com/embed/5uvwfskYwl0'
    }
}; 