const lang = {
    ru: {
        heroDesc: 'Твой пульс к миру игр — системные требования, описания и подборки для любого ПК.',
        heroBtn: 'ПЕРЕЙТИ К ИГРАМ',
        featuresTitle: 'Возможности',
        feat1Title: 'Огромная коллекция',
        feat1Desc: 'Более 50 игр: все части Battlefield, Far Cry, Assassin\'s Creed, Forza Horizon, Assetto Corsa и другие.',
        feat2Title: 'Точные требования',
        feat2Desc: 'Минимальные и рекомендуемые системные требования — официальные данные из Steam и от разработчиков.',
        feat3Title: 'Умный поиск',
        feat3Desc: 'Мгновенная фильтрация по названию с автопрокруткой к первой найденной игре и автоподсказки.',
        feat4Title: 'Детальные описания',
        feat4Desc: 'К каждой игре прилагается развёрнутое описание сюжета, геймплея и особенностей, а также год выпуска и разработчик.',
        feat5Title: 'Стильный дизайн',
        feat5Desc: 'Анимации при наведении, плавные переходы, 4 темы на выбор, движущийся фон с частицами.',
        feat6Title: 'Всегда с тобой',
        feat6Desc: 'Сайт работает в одном файле — можно сохранить и пользоваться офлайн.',
        aboutTitle: 'О сайте',
        about1Title: 'Для кого',
        about1Desc: 'GamePulse создан для геймеров, которые хотят знать, потянет ли их компьютер новинку, а также для тех, кто просто интересуется системными требованиями культовых игр.',
        about2Title: 'Как это работает',
        about2Desc: 'Мы собираем официальные данные из Steam и от разработчиков, структурируем их и добавляем подробные описания. Всё в одном месте — без лишних переходов.',
        about3Title: 'Почему мы',
        about3Desc: 'Удобный интерфейс, постоянное обновление базы, четыре темы оформления и возможность быстро найти нужную игру по названию.',
        navHome: 'Главная',
        navGames: 'Игры',
        navFavorites: 'Избранное',
        navSettings: 'Настройки',
        navPopular: 'Популярные',
        navAssassins: "Assassin's Creed",
        navFarcry: 'Far Cry',
        navGodofwar: 'God of War',
        navHitman: 'Hitman',
        navBattlefield: 'Battlefield',
        navForza: 'Forza Horizon',
        navSimulators: 'Симуляторы',
        popularTitle: 'Популярные игры',
        assassinsTitle: "Assassin's Creed",
        farcryTitle: 'Far Cry',
        godofwarTitle: 'God of War',
        hitmanTitle: 'Hitman',
        battlefieldTitle: 'Battlefield',
        forzaTitle: 'Forza Horizon',
        simulatorsTitle: 'Симуляторы',
        favoritesEmpty: 'Здесь пока пусто. Добавьте игры в избранное, нажав на звёздочку.',
        settingsTitle: 'Настройки',
        langLabel: 'Язык / Language',
        footerText: '© 2026 GamePulse — системные требования из официальных источников. Все права на изображения принадлежат правообладателям.',
        minReqs: 'Минимальные требования',
        recReqs: 'Рекомендуемые',
        doctorTitle: '🤖 Гейм-Доктор',
        closeBtn: 'Закрыть',
        playtime_title: '⏱️ Время прохождения',
        playtime_main: 'Основной сюжет',
        playtime_completion: '100% прохождение',
        ratings_title: '📊 Оценки',
        metacritic_label: 'Metacritic',
        steam_label: 'Steam',
        ign_label: 'IGN',
        build_title: '🧩 Собери идеальный ПК под игру',
        build_cpu: 'Процессор',
        build_gpu: 'Видеокарта',
        build_ram: 'Оперативная память',
        trailer_title: '🎬 Трейлер'
    },
    en: {
        heroDesc: 'Your pulse to the world of games — system requirements, descriptions and collections for any PC.',
        heroBtn: 'GO TO GAMES',
        featuresTitle: 'Features',
        feat1Title: 'Huge Collection',
        feat1Desc: 'More than 50 games: all Battlefield, Far Cry, Assassin\'s Creed, Forza Horizon, Assetto Corsa parts and others.',
        feat2Title: 'Accurate Requirements',
        feat2Desc: 'Minimum and recommended system requirements — official data from Steam and developers.',
        feat3Title: 'Smart Search',
        feat3Desc: 'Instant filtering by title with auto-scroll to the first found game and hints.',
        feat4Title: 'Detailed Descriptions',
        feat4Desc: 'Each game comes with a detailed description of the story, gameplay and features, plus release year and developer.',
        feat5Title: 'Stylish Design',
        feat5Desc: 'Hover animations, smooth transitions, 4 themes to choose from, moving background with particles.',
        feat6Title: 'Always with You',
        feat6Desc: 'The site works in one file — you can save it and use it offline.',
        aboutTitle: 'About',
        about1Title: 'For Whom',
        about1Desc: 'GamePulse is created for gamers who want to know if their computer can handle a new game, and for those who are just interested in the system requirements of iconic games.',
        about2Title: 'How It Works',
        about2Desc: 'We collect official data from Steam and developers, structure it and add detailed descriptions. Everything in one place — no extra transitions.',
        about3Title: 'Why Us',
        about3Desc: 'Convenient interface, constantly updated database, four design themes and the ability to quickly find the right game by name or genre.',
        navHome: 'Home',
        navGames: 'Games',
        navFavorites: 'Favorites',
        navSettings: 'Settings',
        navPopular: 'Popular',
        navAssassins: "Assassin's Creed",
        navFarcry: 'Far Cry',
        navGodofwar: 'God of War',
        navHitman: 'Hitman',
        navBattlefield: 'Battlefield',
        navForza: 'Forza Horizon',
        navSimulators: 'Simulators',
        popularTitle: 'Popular Games',
        assassinsTitle: "Assassin's Creed",
        farcryTitle: 'Far Cry',
        godofwarTitle: 'God of War',
        hitmanTitle: 'Hitman',
        battlefieldTitle: 'Battlefield',
        forzaTitle: 'Forza Horizon',
        simulatorsTitle: 'Simulators',
        favoritesEmpty: 'It\'s empty here. Add games to favorites by clicking on the star.',
        settingsTitle: 'Settings',
        langLabel: 'Language / Язык',
        footerText: '© 2026 GamePulse — system requirements from official sources. All images belong to their respective owners.',
        minReqs: 'Minimum Requirements',
        recReqs: 'Recommended',
        doctorTitle: '🤖 Game Doctor',
        closeBtn: 'Close',
        playtime_title: '⏱️ Playtime',
        playtime_main: 'Main story',
        playtime_completion: '100% completion',
        ratings_title: '📊 Ratings',
        metacritic_label: 'Metacritic',
        steam_label: 'Steam',
        ign_label: 'IGN',
        build_title: '🧩 Build ideal PC for the game',
        build_cpu: 'CPU',
        build_gpu: 'GPU',
        build_ram: 'RAM',
        trailer_title: '🎬 Trailer'
    }
};